### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by rochdev** [jacob-meacham/serverless-plugin-bind-deployment-id#3]
The provided examples doesn't work.

Using `StageDescription` in `AWS::ApiGateway::Deployment` results in a `StageDescription cannot be specified when stage referenced by StageName already exists.` error.

Using the `AWS::ApiGateway::Stage`results in a `An error occurred while provisioning your stack: ApiGatewayStage - dev already exists.` error.

How to actually use this plugin?

**Comment by rochdev** [comment]
When I get it to not error out, it creates an `__unused_stage__` stage besides the actual stage.

**Comment by rochdev** [comment]
According to AWS support center the correct way would be to completely remove the `StageName` from deployment instead of simply renaming it to a dummy value.

**Comment by rochdev** [comment]
Ok it seems the creation of an `__unused_stage__` stage is the expected behavior. However, the example still contains a few errors meaning that it doesn't work as-is.

**Comment by jacob-meacham** [comment]
Fixed README to be more useful
