### ISSUE TITLE
Serverless Error Invalid template resource property as of serverless version 1.12.1

### ISSUE THREAD

**Issue by FritzSG** [jacob-meacham/serverless-plugin-bind-deployment-id#6]
Serverless Error ---------------------------------------
 
     Invalid template resource property '__deployment__'

With the recent deployment of 1.12.1, the current config doesn't seem to work.

**Comment by jaikdean** [comment]
+1

**Comment by jacob-meacham** [comment]
I'll take a look at this today - thanks for filing!
